### ISSUE TITLE
Resolve with Bluebird Promise

### ISSUE THREAD

**Issue by Zn4rK** [markusahlstrand/knex-data-api-client#51]
Great little library! Works great for the most part. I have encountered an issue when I bundle this with webpack, and it seems to be related to how Knex expects (maybe? It's a bit unclear in their code base) Bluebird promises;

```js
this.client.acquireConnection(...).catch(...).disposer
```

Is there a reason the promises at these lines aren't resolved with Bluebird? It is already imported in the bundle. Uncommenting these seems to solve my issues with webpack.
https://github.com/markusahlstrand/knex-data-api-client/blob/5b4cb7dc098deec9a987cf67ae3f96b6c432accb/src/data-api.js#L32
https://github.com/markusahlstrand/knex-data-api-client/blob/5b4cb7dc098deec9a987cf67ae3f96b6c432accb/src/data-api.js#L38

When I'm marking both Knex and this library as externals in Webpack, it works without the need to modify the above source. 

And just for the completeness of the use-case: I'm packing my dependencies with webpack to optimize my cold starts on AWS Lambda.

**Comment by Zn4rK** [comment]
Alright, so I managed to solve this by investigating a bit more, and it seems like I had a dependency that forced an earlier version of Knex.

Although, I would still like to know why those lines are commented though :)

**Comment by markusahlstrand** [comment]
Hi! Great that you managed to get it to work :) I tried to get rid of the Bluebird dependency at one point and replace it with native promises, but.. it turned out that knex didn't like that. I looks like I missed reverting some of the lines to Bluebird promises, so even though it seems to be working now it's probably safer to use Bluebird in all places. I'll see if I can fix this next time I do an update. Thanks!
